version: "3.8"
services:
  # Application service
  web:
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./data:/data
    env_file: .env
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
