version: '3.8'
services:
  # Application service
  web:
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - ./data:/data
    env_file: .env
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge