name: Deploy Services

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Deploy AI Service
        run: |
          ls -la  # List directory contents for debugging
          cd $GITHUB_WORKSPACE/ai || echo "ai directory not found"
          chmod +x cloud_run_deploy.sh
          ./cloud_run_deploy.sh
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Deploy Backend Service
        run: |
          cd $GITHUB_WORKSPACE/backend || echo "backend directory not found"
          chmod +x cloud_run_deploy.sh
          ./cloud_run_deploy.sh
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Deploy Portal Service
        run: |
          cd $GITHUB_WORKSPACE/portal || echo "portal directory not found"
          chmod +x cloud_run_deploy.sh
          ./cloud_run_deploy.sh
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Deploy Landing Page Service
        run: |
          cd $GITHUB_WORKSPACE/landing_page || echo "landing_page directory not found"
          chmod +x cloud_run_deploy.sh
          ./cloud_run_deploy.sh
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Configure Load Balancer
        run: |
          gcloud compute url-maps create my-load-balancer --default-service=landingpage
          gcloud compute url-maps add-path-matcher my-load-balancer \
            --path-matcher-name=pathmap \
            --default-service=landing-page-service \
            --path-rules="/portal/*=portal,/api/*=backend,/ai/*=ainbox"
          gcloud compute forwarding-rules create http-content-rule \
            --global \
            --target-http-proxy=my-load-balancer-proxy \
            --ports=80
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
