name: Deploy Services

on:
  push:
    branches: [main]

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      ai_changed: ${{ steps.check_files.outputs.ai_changed }}
      backend_changed: ${{ steps.check_files.outputs.backend_changed }}
      portal_changed: ${{ steps.check_files.outputs.portal_changed }}
      landing_page_changed: ${{ steps.check_files.outputs.landing_page_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check for file changes
        id: check_files
        run: |
          git diff --name-only HEAD^ HEAD > changes.txt
          echo "ai_changed=$( grep -q '^ai/' changes.txt && echo 'true' || echo 'false' )" >> $GITHUB_OUTPUT
          echo "backend_changed=$( grep -q '^backend/' changes.txt && echo 'true' || echo 'false' )" >> $GITHUB_OUTPUT
          echo "portal_changed=$( grep -q '^portal/' changes.txt && echo 'true' || echo 'false' )" >> $GITHUB_OUTPUT
          echo "landing_page_changed=$( grep -q '^landing_page/' changes.txt && echo 'true' || echo 'false' )" >> $GITHUB_OUTPUT

  deploy:
    needs: check_changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure gcloud CLI
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Deploy AI Service
        if: needs.check_changes.outputs.ai_changed == 'true'
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          cd ai
          chmod +x cloud_run_deploy.sh
          ./cloud_run_deploy.sh

      - name: Deploy Backend Service
        if: needs.check_changes.outputs.backend_changed == 'true'
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          cd backend
          chmod +x cloud_run_deploy.sh
          ./cloud_run_deploy.sh

      - name: Deploy Portal Service
        if: needs.check_changes.outputs.portal_changed == 'true'
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          cd portal
          chmod +x cloud_run_deploy.sh
          ./cloud_run_deploy.sh

      - name: Deploy Landing Page Service
        if: needs.check_changes.outputs.landing_page_changed == 'true'
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          cd landing_page
          chmod +x cloud_run_deploy.sh
          ./cloud_run_deploy.sh
