name: Deploy Services

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Authenticate with Google Cloud
      - id: "auth"
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: latest
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy AI Service
        run: |
          cd ai
          ./cloud_run_deploy.sh

      - name: Deploy Backend Service
        run: |
          cd backend
          ./cloud_run_deploy.sh

      - name: Deploy Portal Service
        run: |
          cd portal
          ./cloud_run_deploy.sh

      - name: Deploy Landing Page Service
        run: |
          cd landing_page
          ./cloud_run_deploy.sh

      - name: Deploy Services and Configure Load Balancer
        run: |
          # Configure Load Balancer
          gcloud compute url-maps create my-load-balancer --default-service=landingpage
          gcloud compute url-maps add-path-matcher my-load-balancer \
            --path-matcher-name=pathmap \
            --default-service=landing-page-service \
            --path-rules="/portal/*=portal,/api/*=backend,/ai/*=ainbox"
          gcloud compute forwarding-rules create http-content-rule \
            --global \
            --target-http-proxy=my-load-balancer-proxy \
            --ports=80
