name: Deploy Services

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure gcloud CLI
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Deploy AI Service
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          cd ai
          chmod +x cloud_run_deploy.sh
          ./cloud_run_deploy.sh

      - name: Deploy Backend Service
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          cd backend
          chmod +x cloud_run_deploy.sh
          ./cloud_run_deploy.sh

      - name: Deploy Portal Service
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          cd portal
          chmod +x cloud_run_deploy.sh
          ./cloud_run_deploy.sh

      - name: Deploy Landing Page Service
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          cd landing_page
          chmod +x cloud_run_deploy.sh
          ./cloud_run_deploy.sh

      - name: Deploy Services and Configure Load Balancer
        run: |
          # Configure Load Balancer
          gcloud compute url-maps create my-load-balancer --default-service=landingpage
          gcloud compute url-maps add-path-matcher my-load-balancer \
            --path-matcher-name=pathmap \
            --default-service=landing-page-service \
            --path-rules="/portal/*=portal,/api/*=backend,/ai/*=ainbox"
          gcloud compute forwarding-rules create http-content-rule \
            --global \
            --target-http-proxy=my-load-balancer-proxy \
            --ports=80
